#운영버전 설정
#logging
logging:
  level:
    org:
      springframework: info

#custom properties
currency-service:
  url: http://prod.com/currency
  username: prodName
  key: prodKey
  
#file upload path
file:
  upload-dir: D:/develop/restful-api-file