#개발버전 설정
#logging
logging:
  level:
    org:
      springframework: debug

#custom properties
currency-service:
  url: http://dev.com/currency
  username: devName
  key: devKey

#actuator의 모든 정보를 볼 수 있음
management:
  server:
    port: 9292
  endpoint:
    health :
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'