#prod, dev 공통 설정
#공백: 스페이스 2칸
spring:
  application:
    name: restful-api

  #profile(e.g. dev, prod, test, qa, ...)
  profiles:
    active: dev
    
  #H2 콘솔 사용 설정
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    url: 'jdbc:cubrid:localhost:33000:testdb:::?charset=UTF-8'
    username: testuser
    password: ictway

  #JPA 설정
  jpa:
    show-sql: true
    hibernate:
      naming: #테이블명의 "."을 Hibernate가 자동으로 "_"로 변환시키기 때문에 "."을 그대로 사용하기 위해 파라미터 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties: 
      hibernate:
        format_sql: true #쿼리가 정렬되서 log에 찍힘
        use_sql_comments: true
    database-platform: org.hibernate.community.dialect.CUBRIDDialect
    
    #h2: data.sql을 사용하여 데이터 생성 시 테이블 즉, @Entity의 테이블이 먼저 생성되게끔 설정(datasource 초기화 및 data.sql 실행을 지연)
    defer-datasource-initialization: true
        
#서버 포트 설정
server:
  port: 9090