#개발버전 설정
#logging
logging:
  level:
    org:
      springframework: debug

#custom properties
currency-service:
  url: http://dev.com/currency
  username: devName
  key: devKey

#actuator의 모든 정보를 볼 수 있음
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
#H2 콘솔 사용 설정(/h2-console)
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb