#개발버전 설정

#logging
logging:
  level:
    org:
      springframework: debug
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#file upload path
file:
  upload-dir: D:/develop/restful-api-file

#actuator의 모든 정보를 볼 수 있음
management:
  server:
    port: 9293
  endpoint:
    health :
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

#CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  
#custom properties
currency-service:
  url: http://dev.com/currency
  username: devName
  key: devKey