#민원시스템

#어플리케이션이 운영되는 서버명
server-type:
  name: CVLCPT #민원
  
site:
  domain: uga.go.kr

spring:
#H2 콘솔 사용 설정
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    #driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    #url: 'jdbc:cubrid:localhost:33000:testdb:::?charset=UTF-8'
    #username: testuser
    #password: ictway
    jndi-name: java:jboss/datasources/CubridRestfulApiDS
    
  jpa:
    properties:
      hibernate:
        default_schema: TESTUSER