#개발버전 설정

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
    kr:
      app:
        restfulapi: DEBUG
        
#file upload path
file:
  upload-dir: D:/develop/restful-api-file

#CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  
#custom properties
currency-service:
  url: http://dev.com/currency
  username: devName
  key: devKey