#prod, dev 공통 설정
#공백: 스페이스 2칸
spring:
  application:
    name: restful-api

  #profile(e.g. dev, prod, test, qa, ...)
  profiles:
    active: dev
    
  #H2 콘솔 사용 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #JPA 설정
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
        
#서버 포트 설정
server:
  port: 9090